#!/usr/bin/env ruby
#^syntax detection

ecosystem "teamserver-ecosystem-1" do

  container "teamserver-app-1" do
    distro "ubuntu"
    release "lucid"
    persist true
    ip "192.168.0.1"
    mac "00:00:5e:35:ea:d5"
    chef_client  ({ :run_list => [] })
  end

end
