# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Auto-generated by cucumber-chef v#{Cucumber::Chef::VERSION} on #{Time.now.utc} -- DO NOT EDIT!

# Vagrant v2 Configuration
###########################
Vagrant.configure("2") do |config|
  config.vm.define "test-lab-#{ENV['USER']}".downcase do |test_lab|
    #test_lab.vm.box = "precise64"
    #test_lab.vm.box_url = "http://files.vagrantup.com/precise64.box"
    test_lab.vm.box = "opscode-ubuntu-12.04-i386"
    test_lab.vm.box_url = "https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04-i386_provisionerless.box"
    test_lab.vm.network :private_network, :ip => "192.168.33.10"


    # This can be set to the host name you wish the guest machine to have. Vagrant
    # will automatically execute the configuration necessary to make this happen.
    config.vm.hostname = "wgsjack199213-starter"

    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine. In the example below,
    # port 8080 on the virtual machine is forwarded to port 9090 on the host.
    # This will allow the virtual machine to communicate of the common proxy port 8080.
    config.vm.network :forwarded_port, guest: 8080, host: 9090


    test_lab.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--cpus", 1]
      vb.customize ["modifyvm", :id, "--memory", 1024]
    end
  end
end
